package io.dsentric

/**
 * Runtime representation of all annotation metadata for a single field.
 *
 * Instances are created by the [[Contract.derived]] macro at compile time;
 * they carry both structural information (required/optional/default) and the
 * full set of constraint/policy flags read from the Java annotations.
 *
 * The [[decoder]] function is also macro-generated and performs type-safe
 * decoding of the raw Any value from a [[RawObject]] to the correct Scala type.
 *
 * @param name        Field name as declared in the case class.
 * @param isOptional  True when the field type is Option[T].
 * @param hasDefault  True when the constructor parameter has a default value.
 * @param isImmutable See @[[io.dsentric.annotations.immutable]].
 * @param isInternal  See @[[io.dsentric.annotations.internal]].
 * @param isReserved  See @[[io.dsentric.annotations.reserved]].
 * @param masked      Some(maskStr) when @[[io.dsentric.annotations.masked]] is present.
 * @param isNonEmpty  See @[[io.dsentric.annotations.nonEmpty]].
 * @param minLength   See @[[io.dsentric.annotations.minLength]].
 * @param maxLength   See @[[io.dsentric.annotations.maxLength]].
 * @param min         See @[[io.dsentric.annotations.min]].
 * @param max         See @[[io.dsentric.annotations.max]].
 * @param pattern     See @[[io.dsentric.annotations.pattern]].
 * @param isEmail     See @[[io.dsentric.annotations.email]].
 * @param isUrl       See @[[io.dsentric.annotations.url]].
 * @param isUuid      See @[[io.dsentric.annotations.uuid]].
 * @param isFuture    See @[[io.dsentric.annotations.future]].
 * @param isPast      See @[[io.dsentric.annotations.past]].
 * @param isPositive  See @[[io.dsentric.annotations.positive]].
 * @param multipleOf  See @[[io.dsentric.annotations.multipleOf]].
 * @param decoder     Macro-generated function: Any => Option[Any]].
 *                    Returns None when the raw value cannot be converted to
 *                    the field's declared type.
 * @param validators     List of custom validators from @[[io.dsentric.annotations.validateWith]].
 *                       Each function accepts the decoded field value (unwrapped from Option)
 *                       and returns a (possibly empty) list of error messages.
 *                       Instantiated once at contract-derivation time by the macro.
 * @param nestedCollect  Optional nested contract validator, generated by the macro when the
 *                       field type is `T`, `Option[T]`, `List[T]`, etc. and `Contract[T]`
 *                       is in scope. Called with the *raw* (pre-decode) field value and the
 *                       field path; returns violations with paths prefixed by basePath.
 * @param nestedSanitize Optional recursive sanitizer. Generated when the field contains
 *                       a nested contract type. Takes the raw field value and returns a
 *                       sanitized version (stripping @internal, masking @masked recursively).
 */
final case class FieldMeta(
  name:           String,
  isOptional:     Boolean,
  hasDefault:     Boolean,
  isImmutable:    Boolean,
  isInternal:     Boolean,
  isReserved:     Boolean,
  masked:         Option[String],
  isNonEmpty:     Boolean,
  minLength:      Option[Int],
  maxLength:      Option[Int],
  min:            Option[Long],
  max:            Option[Long],
  pattern:        Option[String],
  isEmail:        Boolean,
  isUrl:          Boolean,
  isUuid:         Boolean,
  isFuture:       Boolean,
  isPast:         Boolean,
  isPositive:     Boolean,
  multipleOf:     Option[Double],
  extractPattern: Option[String],
  decoder:        Any => Option[Any],
  validators:     List[Any => List[String]]                      = Nil,
  nestedCollect:  Option[(Any, FieldPath) => List[Violation]]    = None,
  nestedPatchCollect: Option[(Any, Any, FieldPath) => List[Violation]] = None,
  nestedSanitize: Option[Any => Any]                             = None,
  /**
   * JSON Schema type hint for this field.
   *
   * Set by the macro at derivation time to one of:
   * `"string"`, `"integer"`, `"number"`, `"boolean"`, `"array"`, `"object"`, or `"any"`.
   *
   * When the field type is `Option[T]`, this reflects the inner type `T`;
   * the optional/required distinction is captured by `isOptional`.
   *
   * `"any"` is used for types the macro cannot resolve (e.g. raw `Either`,
   * `Map`, or custom wrapper types without a nested `Contract`).
   */
  schemaType:     String                          = "any",
  /**
   * JSON Schema type hint for array items.
   *
   * Only meaningful when `schemaType == "array"`.  Carries the primitive type
   * name of the element type (e.g. `"string"`, `"integer"`), or `"object"` /
   * `"any"` for complex element types.
   */
  arrayItemType:  String                          = "any",
  /**
   * Lazy JSON Schema generator for the field's nested contract type.
   *
   * `Some(fn)` is set by the macro when the field type (or its element type
   * for arrays) has a `Contract[T]` in scope.  Calling `fn()` returns the
   * full JSON Schema document for the nested contract.
   *
   * Used by [[io.dsentric.ContractImpl.jsonSchema]] to inline nested object
   * schemas and array-item schemas.
   */
  schemaFn:       Option[() => RawObject]         = None
):
  /** A field is required if it is not optional AND has no default value. */
  def isRequired: Boolean = !isOptional && !hasDefault

  /**
   * Run all constraint checks against an already-decoded value.
   *
   * @param value  The decoded value (unwrapped from Option if needed).
   * @param path   Field path for error reporting.
   * @return       Accumulated list of violations; empty when all pass.
   */
  def validateConstraints(value: Any, path: FieldPath): List[Violation] =
    // Unwrap Option and single-field wrapper types (e.g. @decodable case classes)
    // so that string/numeric constraints apply to the primitive inside the wrapper.
    // Order matters: Option is unwrapped first (Some is also a Product with arity 1).
    val inner: Any = value match
      case Some(v)                                         => v
      case p: Product if p.productArity == 1               => p.productElement(0)
      case other                                           => other

    val buf = collection.mutable.ArrayBuffer.empty[Violation]

    // @nonEmpty
    if isNonEmpty then inner match
      case s: String if s.isEmpty =>
        buf += Violation(path, ViolationCode.ConstraintFailed("nonEmpty"),
          s"'$name' must not be empty")
      case c: Iterable[?] if c.isEmpty =>
        buf += Violation(path, ViolationCode.ConstraintFailed("nonEmpty"),
          s"'$name' must not be empty")
      case _ =>

    // @minLength
    minLength.foreach { ml => inner match
      case s: String if s.length < ml =>
        buf += Violation(path, ViolationCode.ConstraintFailed("minLength"),
          s"'$name' must be at least $ml characters (got ${s.length})")
      case _ =>
    }

    // @maxLength
    maxLength.foreach { ml => inner match
      case s: String if s.length > ml =>
        buf += Violation(path, ViolationCode.ConstraintFailed("maxLength"),
          s"'$name' must be at most $ml characters (got ${s.length})")
      case _ =>
    }

    // @min
    min.foreach { m =>
      val numericValue: Option[Double] = inner match
        case i: Int    => Some(i.toDouble)
        case l: Long   => Some(l.toDouble)
        case f: Float  => Some(f.toDouble)
        case d: Double => Some(d)
        case _         => None
      numericValue.foreach { n =>
        if n < m.toDouble then
          buf += Violation(path, ViolationCode.ConstraintFailed("min"),
            s"'$name' must be >= $m (got $n)")
      }
    }

    // @max
    max.foreach { m =>
      val numericValue: Option[Double] = inner match
        case i: Int    => Some(i.toDouble)
        case l: Long   => Some(l.toDouble)
        case f: Float  => Some(f.toDouble)
        case d: Double => Some(d)
        case _         => None
      numericValue.foreach { n =>
        if n > m.toDouble then
          buf += Violation(path, ViolationCode.ConstraintFailed("max"),
            s"'$name' must be <= $m (got $n)")
      }
    }

    // @pattern
    pattern.foreach { p => inner match
      case s: String =>
        if !s.matches(p) then
          buf += Violation(path, ViolationCode.ConstraintFailed("pattern"),
            s"'$name' does not match required pattern")
      case _ =>
    }

    // @extract (on a contract field — full-match format validation)
    extractPattern.foreach { p => inner match
      case s: String =>
        if !s.matches(p) then
          buf += Violation(path, ViolationCode.ConstraintFailed("extract"),
            s"'$name' does not match required format")
      case _ =>
    }

    // @email  — permissive RFC-5322-ish check
    if isEmail then inner match
      case s: String =>
        val emailRegex = """^[^@\s]+@[^@\s]+\.[^@\s]+$"""
        if !s.matches(emailRegex) then
          buf += Violation(path, ViolationCode.ConstraintFailed("email"),
            s"'$name' is not a valid email address")
      case _ =>

    // @url — valid http/https URL
    if isUrl then inner match
      case s: String =>
        val urlRegex = """^https?://[^\s/$.?#].[^\s]*$"""
        if !s.matches(urlRegex) then
          buf += Violation(path, ViolationCode.ConstraintFailed("url"),
            s"'$name' is not a valid URL")
      case _ =>

    // @uuid — canonical UUID format
    if isUuid then inner match
      case s: String =>
        val uuidRegex = """^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"""
        if !s.matches(uuidRegex) then
          buf += Violation(path, ViolationCode.ConstraintFailed("uuid"),
            s"'$name' is not a valid UUID")
      case _ =>

    // @future — epoch-millis must be in the future
    if isFuture then
      val numericValue: Option[Long] = inner match
        case i: Int  => Some(i.toLong)
        case l: Long => Some(l)
        case _       => None
      numericValue.foreach { ts =>
        if ts <= System.currentTimeMillis() then
          buf += Violation(path, ViolationCode.ConstraintFailed("future"),
            s"'$name' must be a future timestamp (got $ts)")
      }

    // @past — epoch-millis must be in the past
    if isPast then
      val numericValue: Option[Long] = inner match
        case i: Int  => Some(i.toLong)
        case l: Long => Some(l)
        case _       => None
      numericValue.foreach { ts =>
        if ts >= System.currentTimeMillis() then
          buf += Violation(path, ViolationCode.ConstraintFailed("past"),
            s"'$name' must be a past timestamp (got $ts)")
      }

    // @positive — strictly greater than zero
    if isPositive then
      val numericValue: Option[Double] = inner match
        case i: Int    => Some(i.toDouble)
        case l: Long   => Some(l.toDouble)
        case f: Float  => Some(f.toDouble)
        case d: Double => Some(d)
        case _         => None
      numericValue.foreach { n =>
        if n <= 0 then
          buf += Violation(path, ViolationCode.ConstraintFailed("positive"),
            s"'$name' must be positive (got $n)")
      }

    // @multipleOf — value must be divisible by the given divisor.
    // We use the ratio-to-integer check (n/divisor ≈ integer) rather than
    // n % divisor ≈ 0, because floating-point modulo is numerically unstable
    // for fractional divisors like 0.01.
    multipleOf.foreach { divisor =>
      val numericValue: Option[Double] = inner match
        case i: Int    => Some(i.toDouble)
        case l: Long   => Some(l.toDouble)
        case f: Float  => Some(f.toDouble)
        case d: Double => Some(d)
        case _         => None
      numericValue.foreach { n =>
        val ratio = n / divisor
        val nearestInt = math.round(ratio).toDouble
        if math.abs(ratio - nearestInt) > 1e-7 then
          buf += Violation(path, ViolationCode.ConstraintFailed("multipleOf"),
            s"'$name' must be a multiple of $divisor (got $n)")
      }
    }

    // @validateWith — call each custom validator in order, accumulating messages
    validators.foreach { validate =>
      val messages = validate(inner)
      messages.foreach { msg =>
        buf += Violation(path, ViolationCode.ConstraintFailed("validateWith"), msg)
      }
    }

    buf.toList
